version: "3.8"

services:
  tmlserver:
    image: gedasfx/tmodloader-server
    environment:
      - TMLSERVER_VERSION=0.11.8.5                    # Required; tModLoaderServer version
    # - TMLSERVER_AUTOSAVE_INTERVAL=*/2 * * * *       # Optional; CRON expression to specify how ofter to perform saving; defaults to 10 minutes
    volumes:
      - terraria:/data
      - ./serverconfig.txt:/server/serverconfig.txt   # Recommended to use.
    ports:
      - "7777:7777"
    restart: unless-stopped

volumes:
  terraria:
