version: "3.8"

services:
  tmlserver:
    image: gedasfx/tmodloader-server
    environment:
      - TMLSERVER_VERSION=2022.09.47.1                # Required; tModLoaderServer version
    volumes:
      - ./data:/data                                  # Optional, volume is created for this regardless
      - ./serverconfig.txt:/server/serverconfig.txt   # Recommended to mount it this way or edit the generated file.
    ports:
      - "7777:7777"
